"""architecture foundation

Revision ID: f3efc9c81c8d
Revises:
Create Date: 2026-09-24 15:38:57.821779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3efc9c81c8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('evidence_manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('report_sha256', sa.String(length=64), nullable=False),
    sa.Column('previous_record_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_audit_records'))
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_records_audit_id'), ['audit_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_records_created_at_utc'), ['created_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_record_hash'), ['record_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_records_source_sha256'), ['source_sha256'], unique=False)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'archived', name='organization_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('billing_plan_code', sa.String(length=64), nullable=True),
    sa.Column('data_region', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('regulations',
    sa.Column('jurisdiction_code', sa.String(length=16), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('official_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_force', 'upcoming', 'superseded', 'retired', 'proposal', 'voluntary_standard', name='regulation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_snapshot_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_text_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_from IS NULL OR effective_until >= effective_from', name='ck_regulations_effective_date_range'),
    sa.CheckConstraint('source_snapshot_sha256 IS NULL OR length(source_snapshot_sha256) = 64', name='ck_regulations_source_sha256_length'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulations')),
    sa.UniqueConstraint('jurisdiction_code', 'identifier', name='uq_regulations_jurisdiction_identifier')
    )
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulations_jurisdiction_code'), ['jurisdiction_code'], unique=False)

    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('permissions_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('invited', 'active', 'disabled', name='user_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('identity_provider', sa.String(length=100), nullable=True),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('last_authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('identity_provider', 'external_subject', name='uq_users_identity_subject')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(event_hash) = 64', name='ck_audit_events_event_hash_length'),
    sa.CheckConstraint('length(payload_sha256) = 64', name='ck_audit_events_payload_sha256_length'),
    sa.CheckConstraint('previous_event_hash IS NULL OR length(previous_event_hash) = 64', name='ck_audit_events_previous_hash_length'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('organization_id', 'event_hash', name='uq_audit_events_organization_hash')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_audit_events_organization_occurred', ['organization_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)

    op.create_table('memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'suspended', 'revoked', name='membership_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_memberships_invited_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_memberships_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_memberships_organization_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('rules',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('regulation_id', sa.Uuid(), nullable=True),
    sa.Column('rule_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('claim_category', sa.String(length=128), nullable=False),
    sa.Column('sector_code', sa.String(length=64), nullable=True),
    sa.Column('legal_force', sa.Enum('binding_national', 'eu_directive', 'eu_regulation', 'proposal_only', 'voluntary_standard', 'internal_policy', name='rule_legal_force', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('default_risk_level', sa.Enum('low', 'medium', 'high', 'review_required', 'insufficient_information', name='rule_default_risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'superseded', 'retired', name='rule_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_version_number > 0', name='ck_rules_positive_current_version'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rules_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], name=op.f('fk_rules_regulation_id_regulations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_claim_category'), ['claim_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_regulation_id'), ['regulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_rule_key'), ['rule_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_rules_sector_code'), ['sector_code'], unique=False)

    op.create_table('suppliers',
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('country_code IS NULL OR length(country_code) = 2', name='ck_suppliers_country_code_length'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_suppliers_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('organization_id', 'external_reference', name='uq_suppliers_organization_external_reference')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_organization_id'), ['organization_id'], unique=False)

    op.create_table('products',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('country_of_sale', sa.String(length=2), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('country_of_sale IS NULL OR length(country_of_sale) = 2', name='ck_products_country_of_sale_length'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_products_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_products_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('organization_id', 'reference', name='uq_products_organization_reference')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('rule_versions',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('legal_reference', sa.String(length=500), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('expected_evidence_json', sa.JSON(), nullable=False),
    sa.Column('decision_logic_json', sa.JSON(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_rule_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_from IS NULL OR effective_until >= effective_from', name='ck_rule_versions_effective_date_range'),
    sa.CheckConstraint('version_number > 0', name='ck_rule_versions_positive_number'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rule_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_versions_rule_id_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_rule_version_id'], ['rule_versions.id'], name=op.f('fk_rule_versions_supersedes_rule_version_id_rule_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_rule_versions_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_versions')),
    sa.UniqueConstraint('rule_id', 'version_number', name='uq_rule_versions_rule_number')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_id'), ['rule_id'], unique=False)

    op.create_table('analyses',
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('draft', 'queued', 'extracting', 'detecting_claims', 'checking_evidence', 'scoring', 'completed', 'failed', 'cancelled', name='analysis_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analyses_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_analyses_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_analyses_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_analyses_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses')),
    sa.UniqueConstraint('organization_id', 'analysis_key', name='uq_analyses_organization_key')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('documents',
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('document_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.Enum('supplier_declaration', 'product_sheet', 'marketing_asset', 'certificate', 'lca_report', 'environmental_declaration', 'lab_report', 'other', name='document_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('quarantined', 'uploaded', 'processing', 'ready', 'failed', 'archived', 'deleted', name='document_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_documents_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_documents_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_documents_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('organization_id', 'document_key', name='uq_documents_organization_key')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('analysis_versions',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'queued', 'extracting', 'detecting_claims', 'checking_evidence', 'scoring', 'completed', 'failed', 'cancelled', name='analysis_version_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('rulebook_version', sa.String(length=128), nullable=False),
    sa.Column('input_manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('result_sha256', sa.String(length=64), nullable=True),
    sa.Column('overall_risk_level', sa.Enum('low', 'medium', 'high', 'review_required', 'insufficient_information', name='analysis_risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(input_manifest_sha256) = 64', name='ck_analysis_versions_input_sha256_length'),
    sa.CheckConstraint('result_sha256 IS NULL OR length(result_sha256) = 64', name='ck_analysis_versions_result_sha256_length'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_analysis_versions_risk_score'),
    sa.CheckConstraint('version_number > 0', name='ck_analysis_versions_positive_number'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_versions_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analysis_versions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_versions')),
    sa.UniqueConstraint('analysis_id', 'version_number', name='uq_analysis_versions_analysis_number')
    )
    with op.batch_alter_table('analysis_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_versions_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_versions_organization_id'), ['organization_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('source_language', sa.String(length=16), nullable=True),
    sa.Column('extraction_status', sa.Enum('pending', 'running', 'completed', 'failed', 'review_required', name='extraction_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('extraction_engine_version', sa.String(length=64), nullable=True),
    sa.Column('extracted_text_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('extracted_text_sha256', sa.String(length=64), nullable=True),
    sa.Column('extraction_error_code', sa.String(length=128), nullable=True),
    sa.Column('extraction_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('extracted_text_sha256 IS NULL OR length(extracted_text_sha256) = 64', name='ck_document_versions_extracted_sha256_length'),
    sa.CheckConstraint('length(sha256) = 64', name='ck_document_versions_sha256_length'),
    sa.CheckConstraint('page_count IS NULL OR page_count > 0', name='ck_document_versions_positive_pages'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_document_versions_nonnegative_size'),
    sa.CheckConstraint('version_number > 0', name='ck_document_versions_positive_number'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_versions_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_versions_document_number'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_document_versions_storage_key'))
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_sha256'), ['sha256'], unique=False)

    op.create_table('analysis_documents',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('attached_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_documents_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attached_by_user_id'], ['users.id'], name=op.f('fk_analysis_documents_attached_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_analysis_documents_document_version_id_document_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_analysis_documents_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_documents')),
    sa.UniqueConstraint('analysis_id', 'document_version_id', 'purpose', name='uq_analysis_documents_version_purpose')
    )
    with op.batch_alter_table('analysis_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_documents_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_documents_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_documents_organization_id'), ['organization_id'], unique=False)

    op.create_table('certificates',
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('scheme', sa.String(length=128), nullable=False),
    sa.Column('license_number', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('declared', 'pending_verification', 'verified', 'expired', 'rejected', 'out_of_scope', name='certificate_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('registry_name', sa.String(length=255), nullable=True),
    sa.Column('registry_source_url', sa.String(length=2048), nullable=True),
    sa.Column('registry_snapshot_sha256', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('registry_snapshot_sha256 IS NULL OR length(registry_snapshot_sha256) = 64', name='ck_certificates_registry_sha256_length'),
    sa.CheckConstraint('valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from', name='ck_certificates_valid_date_range'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_certificates_document_version_id_document_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_certificates_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_certificates_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_certificates_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_certificates_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('organization_id', 'scheme', 'license_number', name='uq_certificates_organization_scheme_license')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('document_segments',
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('segment_type', sa.Enum('title', 'paragraph', 'table', 'table_cell', 'footnote', 'image_ocr', 'other', name='segment_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('bounding_box_json', sa.JSON(), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(source_sha256) = 64', name='ck_document_segments_sha256_length'),
    sa.CheckConstraint('page_number IS NULL OR page_number > 0', name='ck_document_segments_positive_page'),
    sa.CheckConstraint('sequence_number >= 0', name='ck_document_segments_nonnegative_sequence'),
    sa.CheckConstraint('start_offset IS NULL OR end_offset IS NULL OR end_offset >= start_offset', name='ck_document_segments_valid_offsets'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_segments_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_segments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_segments')),
    sa.UniqueConstraint('document_version_id', 'sequence_number', name='uq_document_segments_version_sequence')
    )
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_segments_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_segments_organization_id'), ['organization_id'], unique=False)

    op.create_table('reports',
    sa.Column('analysis_version_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('report_format', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('requested', 'generating', 'ready', 'failed', 'superseded', name='report_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('sha256 IS NULL OR length(sha256) = 64', name='ck_reports_sha256_length'),
    sa.CheckConstraint('version_number > 0', name='ck_reports_positive_number'),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], name=op.f('fk_reports_analysis_version_id_analysis_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reports_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_reports_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('analysis_version_id', 'version_number', 'report_format', name='uq_reports_analysis_version_format'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_reports_storage_key'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_analysis_version_id'), ['analysis_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_organization_id'), ['organization_id'], unique=False)

    op.create_table('claims',
    sa.Column('analysis_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_segment_id', sa.Uuid(), nullable=True),
    sa.Column('claim_type', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('deterministic', 'ai_candidate', 'human', name='claim_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('detected', 'confirmed', 'dismissed', 'review_required', name='claim_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('detector_version', sa.String(length=128), nullable=True),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_claims_confidence_score'),
    sa.CheckConstraint('start_offset IS NULL OR end_offset IS NULL OR end_offset >= start_offset', name='ck_claims_valid_offsets'),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], name=op.f('fk_claims_analysis_version_id_analysis_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_segment_id'], ['document_segments.id'], name=op.f('fk_claims_document_segment_id_document_segments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_claims_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_analysis_version_id'), ['analysis_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_claim_type'), ['claim_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_document_segment_id'), ['document_segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_organization_id'), ['organization_id'], unique=False)

    op.create_table('evidence',
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('certificate_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.Enum('certificate', 'lca_report', 'environmental_declaration', 'lab_report', 'recycling_route', 'ghg_inventory', 'ghg_reduction_plan', 'carbon_offset', 'standard', 'other', name='evidence_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'present', 'partial', 'missing', 'expired', 'out_of_scope', 'verified', 'rejected', name='evidence_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('product_scope', sa.Text(), nullable=True),
    sa.Column('evidence_metadata_json', sa.JSON(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on', name='ck_evidence_valid_date_range'),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], name=op.f('fk_evidence_certificate_id_certificates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_evidence_document_version_id_document_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_evidence_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_evidence_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_evidence_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_document_version_id'), ['document_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('evidence_links',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('supports', 'partially_supports', 'contradicts', 'not_related', 'review_required', name='evidence_relation', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('coverage_status', sa.Enum('pending', 'present', 'partial', 'missing', 'expired', 'out_of_scope', 'verified', 'rejected', name='evidence_link_coverage_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('validity_as_of', sa.Date(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_evidence_links_confidence_score'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_links_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_evidence_links_evidence_id_evidence'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_links_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_evidence_links_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_links')),
    sa.UniqueConstraint('claim_id', 'evidence_id', name='uq_evidence_links_claim_evidence')
    )
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_links_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_organization_id'), ['organization_id'], unique=False)

    op.create_table('evidence_requests',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'partially_fulfilled', 'fulfilled', 'overdue', 'cancelled', name='evidence_request_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('requested_items_json', sa.JSON(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_requests_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_evidence_requests_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_requests_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_evidence_requests_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_evidence_requests_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_requests'))
    )
    with op.batch_alter_table('evidence_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_requests_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_requests_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_requests_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_requests_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('analysis_version_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'review_required', 'insufficient_information', name='recommendation_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('requires_human_validation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'dismissed', 'implemented', name='recommendation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], name=op.f('fk_recommendations_analysis_version_id_analysis_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_recommendations_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_recommendations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_analysis_version_id'), ['analysis_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_organization_id'), ['organization_id'], unique=False)

    op.create_table('risks',
    sa.Column('analysis_version_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('risk_type', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Enum('low', 'medium', 'high', 'review_required', 'insufficient_information', name='risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=False),
    sa.Column('source_citations_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_risks_score'),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], name=op.f('fk_risks_analysis_version_id_analysis_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_risks_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risks_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_risks_rule_id_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_analysis_version_id'), ['analysis_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_rule_id'), ['rule_id'], unique=False)

    op.create_table('validations',
    sa.Column('analysis_version_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('pending', 'validated', 'contested', 'overridden', name='validation_decision', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], name=op.f('fk_validations_analysis_version_id_analysis_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_validations_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_validations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_validations_reviewer_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validations'))
    )
    with op.batch_alter_table('validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validations_analysis_version_id'), ['analysis_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validations_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validations_reviewer_user_id'), ['reviewer_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validations_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_validations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_validations_claim_id'))
        batch_op.drop_index(batch_op.f('ix_validations_analysis_version_id'))

    op.drop_table('validations')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_rule_id'))
        batch_op.drop_index(batch_op.f('ix_risks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_risks_claim_id'))
        batch_op.drop_index(batch_op.f('ix_risks_analysis_version_id'))

    op.drop_table('risks')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_claim_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_analysis_version_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('evidence_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_requests_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_requests_product_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_requests_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_evidence_requests_claim_id'))

    op.drop_table('evidence_requests')
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_links_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_claim_id'))

    op.drop_table('evidence_links')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_product_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_evidence_certificate_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_organization_id'))
        batch_op.drop_index(batch_op.f('ix_claims_document_segment_id'))
        batch_op.drop_index(batch_op.f('ix_claims_claim_type'))
        batch_op.drop_index(batch_op.f('ix_claims_category'))
        batch_op.drop_index(batch_op.f('ix_claims_analysis_version_id'))

    op.drop_table('claims')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reports_analysis_version_id'))

    op.drop_table('reports')
    with op.batch_alter_table('document_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_segments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_document_segments_document_version_id'))

    op.drop_table('document_segments')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_product_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_deleted_at'))

    op.drop_table('certificates')
    with op.batch_alter_table('analysis_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_documents_document_version_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_documents_analysis_id'))

    op.drop_table('analysis_documents')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_sha256'))
        batch_op.drop_index(batch_op.f('ix_document_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('analysis_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_versions_analysis_id'))

    op.drop_table('analysis_versions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_documents_product_id'))
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_documents_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_documents_created_by_user_id'))

    op.drop_table('documents')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_product_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_deleted_at'))

    op.drop_table('analyses')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_versions_organization_id'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))
        batch_op.drop_index(batch_op.f('ix_products_deleted_at'))

    op.drop_table('products')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_deleted_at'))

    op.drop_table('suppliers')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_sector_code'))
        batch_op.drop_index(batch_op.f('ix_rules_rule_key'))
        batch_op.drop_index(batch_op.f('ix_rules_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_rules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_rules_claim_category'))

    op.drop_table('rules')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_role_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index('ix_audit_events_organization_occurred')
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulations_jurisdiction_code'))

    op.drop_table('regulations')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_source_sha256'))
        batch_op.drop_index(batch_op.f('ix_audit_records_record_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_records_created_at_utc'))
        batch_op.drop_index(batch_op.f('ix_audit_records_audit_id'))

    op.drop_table('audit_records')
    # ### end Alembic commands ###
